# Generated by Django 5.2.4 on 2025-11-16 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='response_value',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='stakeholder',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('rating', 'Rating (1–5)'), ('mcq', 'Multiple Choice')], default='rating', max_length=10),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='feedback.question')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
